
# set compile time as current UNIX timestamp
CXXFLAGS += -fno-strict-aliasing
ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM*
USER_LIB_PATH = ../lib
ARDUINO_LIBS = WSWireLib/Library/WSWire SdFat/SdFat Arducom
include /usr/share/arduino/Arduino.mk
