
# set compile time as current UNIX timestamp
CXXFLAGS += -fno-strict-aliasing
ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB*
USER_LIB_PATH = ../lib
ARDUINO_LIBS = WSWire SdFat/SdFat Arducom
include /usr/share/arduino/Arduino.mk
