
CXXFLAGS += -fno-strict-aliasing
ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB*
USER_LIB_PATH = ../lib
ARDUINO_LIBS = SPI WSWireLib WSWireLib/utility SdFat Ethernet Ethernet/utility Arducom
include /usr/share/arduino/Arduino.mk
