
CXXFLAGS += -fno-strict-aliasing
ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM*
ARDUINO_LIBS = SPI SoftwareSerial DHTlib RTClib SdFat SdFat/utility Wire Wire/utility EEPROM Arducom
include /usr/share/arduino/Arduino.mk
