ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM*
USER_LIB_PATH = ../lib
ARDUINO_LIBS = SPI WSRTClib SdFat/SdFat WSWireLib/Library/WSWire EEPROM Arducom
include /usr/share/arduino/Arduino.mk
