ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyS0
USER_LIB_PATH = ../lib
ARDUINO_LIBS = SPI SoftwareSerial WSRTClib SdFat/SdFat SdFat/SdFat/utility WSWireLib/Library/WSWire WSWireLib/Library/WSWire/utility Ethernet WiFiEsp/src WiFiEsp/src/utility EEPROM Arducom
include /usr/share/arduino/Arduino.mk
