ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB*
USER_LIB_PATH = ../lib
ARDUINO_LIBS = SPI WSRTClib SdFat/SdFat SdFat/SdFat/utility WSWireLib/Library/WSWire WSWireLib/Library/WSWire/utility EEPROM Arducom
include /usr/share/arduino/Arduino.mk
